/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class BackgroundImage {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected BackgroundImage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BackgroundImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_BackgroundImage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BackgroundImage() {
    this(AdaptiveCardObjectModelJNI.new_BackgroundImage(), true);
  }

  public void SetType(String value) {
    AdaptiveCardObjectModelJNI.BackgroundImage_SetType(swigCPtr, this, value);
  }

  public String GetType() {
    return AdaptiveCardObjectModelJNI.BackgroundImage_GetType(swigCPtr, this);
  }

  public void SetMode(String value) {
    AdaptiveCardObjectModelJNI.BackgroundImage_SetMode(swigCPtr, this, value);
  }

  public String GetMode() {
    return AdaptiveCardObjectModelJNI.BackgroundImage_GetMode(swigCPtr, this);
  }

  public void SetUrl(String value) {
    AdaptiveCardObjectModelJNI.BackgroundImage_SetUrl(swigCPtr, this, value);
  }

  public String GetUrl() {
    return AdaptiveCardObjectModelJNI.BackgroundImage_GetUrl(swigCPtr, this);
  }

  public void SetHorizontalAlignment(HorizontalAlignment value) {
    AdaptiveCardObjectModelJNI.BackgroundImage_SetHorizontalAlignment(swigCPtr, this, value.swigValue());
  }

  public HorizontalAlignment GetHorizontalAlignment() {
    return HorizontalAlignment.swigToEnum(AdaptiveCardObjectModelJNI.BackgroundImage_GetHorizontalAlignment(swigCPtr, this));
  }

  public void SetVerticalAlignment(VerticalAlignment value) {
    AdaptiveCardObjectModelJNI.BackgroundImage_SetVerticalAlignment(swigCPtr, this, value.swigValue());
  }

  public VerticalAlignment GetVerticalAlignment() {
    return VerticalAlignment.swigToEnum(AdaptiveCardObjectModelJNI.BackgroundImage_GetVerticalAlignment(swigCPtr, this));
  }

  public static BackgroundImage Deserialize(JsonValue root) {
    long cPtr = AdaptiveCardObjectModelJNI.BackgroundImage_Deserialize(JsonValue.getCPtr(root), root);
    return (cPtr == 0) ? null : new BackgroundImage(cPtr, true);
  }

}
