/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class Height {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Height(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Height obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_Height(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Height() {
    this(AdaptiveCardObjectModelJNI.new_Height__SWIG_0(), true);
  }

  public Height(HeightType heightType) {
    this(AdaptiveCardObjectModelJNI.new_Height__SWIG_1(heightType.swigValue()), true);
  }

  public HeightType GetHeightType() {
    return HeightType.swigToEnum(AdaptiveCardObjectModelJNI.Height_GetHeightType(swigCPtr, this));
  }

  public void SetHeightType(HeightType value) {
    AdaptiveCardObjectModelJNI.Height_SetHeightType(swigCPtr, this, value.swigValue());
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.Height_Serialize(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.Height_SerializeToJsonValue(swigCPtr, this), true);
  }

  public static Height Deserialize(JsonValue root) {
    return new Height(AdaptiveCardObjectModelJNI.Height_Deserialize(JsonValue.getCPtr(root), root), true);
  }

  public static Height DeserializeFromString(String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.Height_DeserializeFromString(jsonString);
    return (cPtr == 0) ? null : new Height(cPtr, true);
  }

}
