#include <sdkddkver.h>

import "windowscontracts.idl";
import "inspectable.idl";
import "Windows.Foundation.idl";
import "Windows.UI.Xaml.idl";
import "Windows.Data.Json.idl";

namespace AdaptiveCards { namespace Rendering { namespace Uwp
{
    runtimeclass AdaptiveCardResourceResolvers;
    runtimeclass AdaptiveCardGetResourceStreamArgs;
    runtimeclass AdaptiveColorsConfig;
    runtimeclass AdaptiveHostConfig;
    runtimeclass RenderedAdaptiveCard;
    runtimeclass AdaptiveActionEventArgs;
    runtimeclass AdaptiveInputs;
    runtimeclass AdaptiveCardParseResult;
    runtimeclass AdaptiveHostConfigParseResult;

    runtimeclass AdaptiveElementParserRegistration;
    runtimeclass AdaptiveActionParserRegistration;
    runtimeclass AdaptiveElementRendererRegistration;
    runtimeclass AdaptiveRenderArgs;

    interface IAdaptiveCardResourceResolver;
    interface IAdaptiveCardElement;
    interface IAdaptiveActionElement;
    interface IAdaptiveColumn;
    interface IAdaptiveFact;
    interface IAdaptiveChoiceInput;
    interface IAdaptiveError;
    interface IAdaptiveWarning;
    interface IRenderedAdaptiveCard;
    interface IAdaptiveElementParser;
    interface IAdaptiveActionParser;
    interface IAdaptiveElementRenderer;

    enum TextSize
    {
        Small = 0,
        Default,
        Medium,
        Large,
        ExtraLarge
    };

    enum TextWeight
    {
        Lighter = 0,
        Default,
        Bolder
    };

    enum ForegroundColor
    {
        Default = 0,
        Dark,
        Light,
        Accent,
        Good,
        Warning,
        Attention
    };

    enum HAlignment
    {
        Left = 0,
        Center,
        Right
    };

    enum ElementType
    {
        Unsupported = 0,
        AdaptiveCard,
        TextBlock,
        Image,
        Container,
        Column,
        ColumnSet,
        FactSet,
        Fact,
        ImageSet,
        ChoiceInput,
        ChoiceSetInput,
        DateInput,
        NumberInput,
        TextInput,
        TimeInput,
        ToggleInput,
        Custom
    };

    enum ActionType
    {
        Unsupported = 0,
        ShowCard,
        Submit,
        OpenUrl,
        Custom
    };

    enum ImageStyle {
        Default = 0,
        Person
    };

    enum ImageSize {
        None = 0,
        Auto,
        Stretch,
        Small,
        Medium,
        Large
    };

    enum SeparatorThickness {
        Default = 0,
        Thick,
    };

    enum Spacing {
        Default = 0,
        None,
        Small,
        Medium,
        Large,
        ExtraLarge,
        Padding
    };

    enum ActionsOrientation {
        Vertical = 0,
        Horizontal
    };

    enum ActionAlignment {
        Left = 0,
        Center,
        Right,
        Stretch,
    };

    enum ActionMode {
        Inline = 0,
        Popup
    };

    enum ChoiceSetStyle {
        Compact = 0,
        Expanded
    };

    enum TextInputStyle {
        Text = 0,
        Tel,
        Url,
        Email,
    };

    enum ContainerStyle {
        None = 0,
        Default,
        Emphasis
    };

    enum ErrorStatusCode {
        InvalidJson = 0,
        RenderFailed,
        RequiredPropertyMissing,
        InvalidPropertyValue,
        UnsupportedParserOverride
    };

    enum WarningStatusCode {
        UnknownElementType = 0,
        UnknownPropertyOnElement,
        UnknownEnumValue,
        NoRendererForType,
        InteractivityNotSupported,
        MaxActionsExceeded,
        AssetLoadFailed,
        UnsupportedSchemaVersion,
    };

    declare
    {
        interface Windows.Foundation.Collections.IVector<IAdaptiveCardElement*>;
        interface Windows.Foundation.Collections.IVector<IAdaptiveActionElement*>;
        interface Windows.Foundation.Collections.IVector<IAdaptiveColumn*>;
        interface Windows.Foundation.Collections.IVector<IAdaptiveFact*>;
        interface Windows.Foundation.Collections.IVector<IAdaptiveChoiceInput*>;
        interface Windows.Foundation.Collections.IVector<IAdaptiveError*>;
        interface Windows.Foundation.Collections.IVector<IAdaptiveWarning*>;
        interface Windows.Foundation.Collections.IObservableVector<IAdaptiveCardElement*>;
        interface Windows.Foundation.Collections.IObservableVector<IAdaptiveColumn*>;
        interface Windows.Foundation.Collections.IObservableVector<IAdaptiveColumn*>;
        interface Windows.Foundation.IAsyncOperation<RenderedAdaptiveCard*>;
        interface Windows.Foundation.IReference<Windows.UI.Text.FontWeight>;
    }

    interface IAdaptiveCardElement : IInspectable
    {
        ElementType ElementType{ get; };
        String ElementTypeString{ get; };
        Spacing Spacing{ get; set; };
        Boolean Separator{ get; set; };
        String Id{ get; set; };
        Windows.Data.Json.JsonObject AdditionalProperties{ get; set; };

        Windows.Data.Json.JsonObject ToJson();
    };

    runtimeclass AdaptiveSeparator
    {
        AdaptiveSeparator();
        ForegroundColor Color{ get; set; };
        SeparatorThickness Thickness{ get; set; };
    };

    runtimeclass AdaptiveTextBlock : IAdaptiveCardElement
    {
        AdaptiveTextBlock();
        TextSize Size{ get; set; };
        TextWeight Weight{ get; set; };
        ForegroundColor Color{ get; set; };
        String Text{ get; set; };
        Boolean IsSubtle{ get; set; };
        Boolean Wrap{ get; set; };
        HAlignment HorizontalAlignment{ get; set; };
        UInt32 MaxLines{ get; set; };
        String Language{ get; set; };
    };

    runtimeclass AdaptiveCard
    {
        AdaptiveCard();

        Windows.Foundation.Collections.IVector<IAdaptiveCardElement*> Body{ get; };
        Windows.Foundation.Collections.IVector<IAdaptiveActionElement*> Actions{ get; };

        ElementType ElementType{ get; };
        String Version{ get; set; };
        String FallbackText{ get; set; };
        Windows.Foundation.Uri BackgroundImage{ get; set; };
        String Speak{ get; set; };
        ContainerStyle Style{ get; set; };

        Windows.Data.Json.JsonObject ToJson();
        
        [overload("FromJson")]
        static AdaptiveCardParseResult FromJson(Windows.Data.Json.JsonObject adaptiveJson);

        [overload("FromJson")]
        static AdaptiveCardParseResult FromJsonWithParserRegistration(
            Windows.Data.Json.JsonObject adaptiveJson,
            AdaptiveElementParserRegistration elementRegistration,
            AdaptiveActionParserRegistration actionRegistration);

        [overload("FromJsonString")]
        static AdaptiveCardParseResult FromJsonString(String adaptiveJson);

        [overload("FromJsonString")]
        static AdaptiveCardParseResult FromJsonStringWithParserRegistration(
            String adaptiveJson,
            AdaptiveElementParserRegistration elementRegistration,
            AdaptiveActionParserRegistration actionRegistration);
    };

    runtimeclass AdaptiveCardParseResult
    {
        AdaptiveCardParseResult();
        AdaptiveCard AdaptiveCard{ get; };
        Windows.Foundation.Collections.IVector<IAdaptiveError*> Errors{ get; };
        Windows.Foundation.Collections.IVector<IAdaptiveWarning*> Warnings{ get; };
    };

    interface IAdaptiveImage : IInspectable 
    {
        Windows.Foundation.Uri Url{ get; set; };
        ImageStyle Style{ get; set; };
        ImageSize Size{ get; set; };
        HAlignment HorizontalAlignment{ get; set; };
        String AltText{ get; set; };
        IAdaptiveActionElement SelectAction{ get; set; };
    };

    runtimeclass AdaptiveImage : IAdaptiveImage, IAdaptiveCardElement
    {
        AdaptiveImage();
    };

    runtimeclass AdaptiveImageSet : IAdaptiveCardElement
    {
        AdaptiveImageSet();
        Windows.Foundation.Collections.IVector<IAdaptiveImage*> Images{ get; };
        ImageSize ImageSize{ get; set; };
    };

    interface IAdaptiveInputElement : IInspectable
    {
        Boolean IsRequired{ get; set; };
    };

    interface IAdaptiveChoiceInput 
    {
        ElementType ElementType{ get; };

        String Title{ get; set; };
        String Value{ get; set; };
    };

    runtimeclass AdaptiveChoiceInput : IAdaptiveChoiceInput
    {
        AdaptiveChoiceInput();
    };

    runtimeclass AdaptiveChoiceSetInput : IAdaptiveInputElement, IAdaptiveCardElement
    {
        AdaptiveChoiceSetInput();
    
        String Value{ get; set; };
        Boolean IsMultiSelect{ get; set; };
        ChoiceSetStyle ChoiceSetStyle{ get; set; };

        Windows.Foundation.Collections.IVector<IAdaptiveChoiceInput*> Choices{ get; };
    };

    runtimeclass AdaptiveDateInput : IAdaptiveInputElement, IAdaptiveCardElement
    {
        AdaptiveDateInput();

        String Max{ get; set; };
        String Min{ get; set; };
        String Placeholder{ get; set; };
        String Value{ get; set; };
    };

    runtimeclass AdaptiveNumberInput : IAdaptiveInputElement, IAdaptiveCardElement
    {
        AdaptiveNumberInput();

        INT32 Max{ get; set; };
        INT32 Min{ get; set; };
        String Placeholder{ get; set; };
        INT32 Value{ get; set; };
    };

    runtimeclass AdaptiveTextInput : IAdaptiveInputElement, IAdaptiveCardElement
    {
        AdaptiveTextInput();

        Boolean IsMultiline{ get; set; };
        UINT32 MaxLength{ get; set; };
        String Placeholder{ get; set; };
        String Value{ get; set; };
        TextInputStyle TextInputStyle{ get; set; };
    };

    runtimeclass AdaptiveTimeInput : IAdaptiveInputElement, IAdaptiveCardElement
    {
        AdaptiveTimeInput();

        String Max{ get; set; };
        String Min{ get; set; };
        String Placeholder{ get; set; };
        String Value{ get; set; };
    };

    runtimeclass AdaptiveToggleInput : IAdaptiveInputElement, IAdaptiveCardElement
    {
        AdaptiveToggleInput();

        String Title{ get; set; };
        String Value{ get; set; };
        String ValueOff{ get; set; };
        String ValueOn{ get; set; };
    };

    runtimeclass AdaptiveContainer : IAdaptiveCardElement
    {
        AdaptiveContainer();
        ContainerStyle Style{ get; set; };
        Windows.Foundation.Collections.IVector<IAdaptiveCardElement*> Items{ get; };
        IAdaptiveActionElement SelectAction{ get; set; };
    };

    interface IAdaptiveColumn : IInspectable
    {
        String Width{ get; set; };
        ContainerStyle Style{ get; set; };
        Windows.Foundation.Collections.IVector<IAdaptiveCardElement*> Items{ get; };
        IAdaptiveActionElement SelectAction{ get; set; };
    };

    runtimeclass AdaptiveColumn : IAdaptiveColumn, IAdaptiveCardElement
    {
        AdaptiveColumn();
    };

    runtimeclass AdaptiveColumnSet : IAdaptiveCardElement
    {
        AdaptiveColumnSet();
        Windows.Foundation.Collections.IVector<IAdaptiveColumn*> Columns{ get; };
        IAdaptiveActionElement SelectAction{ get; set; };
    };

    interface IAdaptiveFact : IInspectable
    {
        ElementType ElementType{ get; };
        String Title{ get; set; };
        String Value{ get; set; };
    };

    runtimeclass AdaptiveFact : IAdaptiveFact
    {
        AdaptiveFact();
    };

    runtimeclass AdaptiveFactSet : IAdaptiveCardElement
    {
        AdaptiveFactSet();
        Windows.Foundation.Collections.IVector<IAdaptiveFact*> Facts{ get; };
    };

    runtimeclass AdaptiveCardRenderer 
    {
        AdaptiveCardRenderer();
        AdaptiveCardResourceResolvers ResourceResolvers{ get; };
        AdaptiveHostConfig HostConfig{ get; set; };

        Windows.UI.Xaml.ResourceDictionary OverrideStyles{ get; set; };

        void SetFixedDimensions(UInt32 desiredWidth, UInt32 desiredHeight);
        void ResetFixedDimensions();

        RenderedAdaptiveCard RenderAdaptiveCard(AdaptiveCard adaptiveCard);
        RenderedAdaptiveCard RenderAdaptiveCardFromJsonString(String adaptiveJson);
        RenderedAdaptiveCard RenderAdaptiveCardFromJson(Windows.Data.Json.JsonObject adaptiveJson);

        AdaptiveElementRendererRegistration ElementRenderers{ get; };
    };

    runtimeclass AdaptiveActionEventArgs
    {
        IAdaptiveActionElement Action{ get; };
        AdaptiveInputs Inputs{ get; };
    }

    runtimeclass AdaptiveContainerStyleDefinition
    {
        AdaptiveContainerStyleDefinition();
        Windows.UI.Color BackgroundColor{ get; set; };
        AdaptiveColorsConfig ForegroundColors{ get; set; };
    };

    runtimeclass AdaptiveContainerStylesDefinition
    {
        AdaptiveContainerStylesDefinition();
        AdaptiveContainerStyleDefinition Default{ get; set; };
        AdaptiveContainerStyleDefinition Emphasis{ get; set; };
    };

    runtimeclass AdaptiveFontSizesConfig 
    {
        AdaptiveFontSizesConfig();
        UInt32 Small{ get; set; };
        UInt32 Default{ get; set; };
        UInt32 Medium{ get; set; };
        UInt32 Large{ get; set; };
        UInt32 ExtraLarge{ get; set; };
    };

    runtimeclass AdaptiveFontWeightsConfig
    {
        AdaptiveFontWeightsConfig();
        UInt16 Lighter{ get; set; };
        UInt16 Default{ get; set; };
        UInt16 Bolder{ get; set; };
    };

    runtimeclass AdaptiveColorConfig
    {
        AdaptiveColorConfig();
        Windows.UI.Color Default{ get; set; };
        Windows.UI.Color Subtle{ get; set; };
    };

    runtimeclass AdaptiveColorsConfig
    {
        AdaptiveColorsConfig();
        AdaptiveColorConfig Default{ get; set; };
        AdaptiveColorConfig Accent{ get; set; };
        AdaptiveColorConfig Dark{ get; set; };
        AdaptiveColorConfig Light{ get; set; };
        AdaptiveColorConfig Good{ get; set; };
        AdaptiveColorConfig Warning{ get; set; };
        AdaptiveColorConfig Attention{ get; set; };
    };

    runtimeclass AdaptiveTextConfig
    {
        AdaptiveTextConfig();
        TextWeight Weight{ get; set; };
        TextSize Size{ get; set; };
        ForegroundColor Color{ get; set; };
        Boolean IsSubtle{ get; set; };
        Boolean Wrap{ get; set; };
        UInt32 MaxWidth{ get; set; };
    };

    runtimeclass AdaptiveSpacingConfig
    {
        AdaptiveSpacingConfig();
        UInt32 Small{ get; set; };
        UInt32 Default{ get; set; };
        UInt32 Medium{ get; set; };
        UInt32 Large{ get; set; };
        UInt32 ExtraLarge{ get; set; };
        UInt32 Padding{ get; set; };
    };

    runtimeclass AdaptiveSeparatorConfig
    {
        AdaptiveSeparatorConfig();
        UInt32 LineThickness{ get; set; };
        Windows.UI.Color LineColor{ get; set; };
    };

    runtimeclass AdaptiveImageSizesConfig
    {
        AdaptiveImageSizesConfig();
        UInt32 Small{ get; set; };
        UInt32 Medium{ get; set; };
        UInt32 Large{ get; set; };
    };

    runtimeclass AdaptiveImageSetConfig
    {
        AdaptiveImageSetConfig();
        ImageSize ImageSize{ get; set; };
        UInt32 MaxImageHeight{ get; set; };
    };

    runtimeclass AdaptiveImageConfig
    {
        AdaptiveImageConfig();
        ImageSize ImageSize{ get; set; };
    };

    runtimeclass AdaptiveCardConfig
    {
        AdaptiveCardConfig();
        Boolean AllowCustomStyle{ get; set; };
    };

    runtimeclass AdaptiveFactSetConfig
    {
        AdaptiveFactSetConfig();
        AdaptiveTextConfig Title{ get; set; };
        AdaptiveTextConfig Value{ get; set; };
        UInt32 Spacing{ get; set; };
    };

    runtimeclass AdaptiveShowCardActionConfig
    {
        AdaptiveShowCardActionConfig();
        ActionMode ActionMode{ get; set; };
        ContainerStyle Style{ get; set; };
        UInt32 InlineTopMargin{ get; set; };
    };

    runtimeclass AdaptiveActionsConfig
    {
        AdaptiveActionsConfig();
        AdaptiveShowCardActionConfig ShowCard{ get; set; };
        ActionsOrientation ActionsOrientation{ get; set; };
        ActionAlignment ActionAlignment{ get; set; };
        UInt32 ButtonSpacing{ get; set; };
        UInt32 MaxActions{ get; set; };
        Spacing Spacing{ get; set; };
    };

    runtimeclass AdaptiveHostConfig
    {
        AdaptiveHostConfig();
        String FontFamily{ get; set; };
        AdaptiveFontSizesConfig FontSizes{ get; set; };
        AdaptiveFontWeightsConfig FontWeights{ get; set; };
        Boolean SupportsInteractivity{ get; set; };
        AdaptiveContainerStylesDefinition ContainerStyles{ get; set; };
        AdaptiveImageSizesConfig ImageSizes{ get; set; };
        AdaptiveSeparatorConfig Separator{ get; set; };
        AdaptiveSpacingConfig Spacing{ get; set; };
        AdaptiveCardConfig AdaptiveCard{ get; set; };
        AdaptiveImageSetConfig ImageSet{ get; set; };
        AdaptiveImageConfig Image{ get; set; };
        AdaptiveFactSetConfig FactSet{ get; set; };
        AdaptiveActionsConfig Actions{ get; set; };

        static AdaptiveHostConfigParseResult FromJsonString(String hostConfigJson);
        static AdaptiveHostConfigParseResult FromJson(Windows.Data.Json.JsonObject hostConfigJson);
    };

    runtimeclass AdaptiveHostConfigParseResult
    {
        AdaptiveHostConfigParseResult();
        AdaptiveHostConfig HostConfig{ get; };
        Windows.Foundation.Collections.IVector<IAdaptiveError*> Errors{ get; };
    };

    interface IAdaptiveActionElement : IInspectable
    {
        ActionType ActionType{ get; };
        String ActionTypeString{ get; };

        String Title{ get; set; };
        String Id{ get; set; };
        Windows.Data.Json.JsonObject AdditionalProperties{ get; set; };

        Windows.Data.Json.JsonObject ToJson();
    };

    runtimeclass AdaptiveOpenUrlAction : IAdaptiveActionElement
    {
        AdaptiveOpenUrlAction();
        Windows.Foundation.Uri Url{ get; set; };
    };

    runtimeclass AdaptiveShowCardAction : IAdaptiveActionElement
    {
        AdaptiveShowCardAction();
        AdaptiveCard Card{ get; set; };
    };


    runtimeclass AdaptiveSubmitAction : IAdaptiveActionElement
    {
        AdaptiveSubmitAction();
        Windows.Data.Json.JsonValue DataJson{ get; set; };
    };

    runtimeclass AdaptiveCardResourceResolvers
    {
        AdaptiveCardResourceResolvers();
        void Set(String scheme, IAdaptiveCardResourceResolver resolver);
        IAdaptiveCardResourceResolver Get(String scheme);
    };

    interface IAdaptiveCardResourceResolver : IInspectable
    {
        Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IRandomAccessStream*> GetResourceStreamAsync(AdaptiveCardGetResourceStreamArgs args);
    };

    runtimeclass AdaptiveCardGetResourceStreamArgs
    {
        AdaptiveCardGetResourceStreamArgs(Windows.Foundation.Uri uri);
        Windows.Foundation.Uri Url{ get; };
    };

    [
        uuid(7bf9ceac-105c-421a-8b4e-8e5be9ead986),
        version(NTDDI_WIN10_RS1),
        exclusiveto(RenderedAdaptiveCard)
    ]
    interface IRenderedAdaptiveCard : IInspectable
    {
        [propget] HRESULT OriginatingCard([out, retval] AdaptiveCard** value);

        [propget] HRESULT FrameworkElement([out, retval] Windows.UI.Xaml.FrameworkElement** value);

        [propget] HRESULT UserInputs([out, retval] AdaptiveInputs** value);

        [propget] HRESULT Errors([out, retval] Windows.Foundation.Collections.IVector<IAdaptiveError*>** value);

        [propget] HRESULT Warnings([out, retval] Windows.Foundation.Collections.IVector<IAdaptiveWarning*>** value);

        [eventadd] HRESULT Action([in] Windows.Foundation.TypedEventHandler<RenderedAdaptiveCard*, AdaptiveActionEventArgs*>* pHandler, [out][retval] EventRegistrationToken* pToken);
        [eventremove] HRESULT Action([in] EventRegistrationToken token);
    };

    [
        version(NTDDI_WIN10_RS1),
        activatable(NTDDI_WIN10_RS1)
    ]
    runtimeclass RenderedAdaptiveCard
    {
        [default] interface IRenderedAdaptiveCard;
    };

    runtimeclass AdaptiveInputs
    {
        AdaptiveInputs();
        Windows.Data.Json.JsonObject AsJson();
        Windows.Foundation.Collections.ValueSet AsValueSet();
    };

    interface IAdaptiveElementParser : IInspectable
    {
        IAdaptiveCardElement FromJson(
            Windows.Data.Json.JsonObject inputJson,
            AdaptiveElementParserRegistration elementParsers,
            AdaptiveActionParserRegistration actionParsers);
    };

    runtimeclass AdaptiveElementParserRegistration
    {
        AdaptiveElementParserRegistration();
        void Set(String type, IAdaptiveElementParser parser);
        IAdaptiveElementParser Get(String type);
        void Remove(String type);
    };

    runtimeclass AdaptiveActionParserRegistration
    {
        AdaptiveActionParserRegistration();
        void Set(String type, IAdaptiveActionParser parser);
        IAdaptiveActionParser Get(String type);
        void Remove(String type);
    };

    interface IAdaptiveActionParser : IInspectable
    {
        IAdaptiveActionElement FromJson(
            Windows.Data.Json.JsonObject inputJson,
            AdaptiveElementParserRegistration elementParsers,
            AdaptiveActionParserRegistration actionParsers);
    };

    runtimeclass AdaptiveElementRendererRegistration
    {
        AdaptiveElementRendererRegistration();
        void Set(String type, IAdaptiveElementRenderer parser);
        IAdaptiveElementRenderer Get(String type);
        void Remove(String type);
    };

    runtimeclass AdaptiveActionInvoker
    {
        AdaptiveActionInvoker();
        void SendActionEvent(IAdaptiveActionElement actionElement);
    };

    interface IAdaptiveInputValue : IInspectable
    {
        IAdaptiveInputElement InputElement{ get; };
        String CurrentValue{ get; };
    };

    runtimeclass AdaptiveRenderContext
    {
        AdaptiveRenderContext();
        AdaptiveHostConfig HostConfig{ get; };
        AdaptiveElementRendererRegistration ElementRenderers{ get; };
        AdaptiveCardResourceResolvers ResourceResolvers{ get; };
        AdaptiveActionInvoker ActionInvoker{ get; };
        Windows.UI.Xaml.ResourceDictionary OverrideStyles{ get; };

        void AddInputValue(IAdaptiveInputValue inputValue);
        void AddError(ErrorStatusCode statusCode, String message);
        void AddWarning(WarningStatusCode statusCode, String message);
    };

    interface IAdaptiveElementRenderer : IInspectable
    {
        Windows.UI.Xaml.UIElement Render(IAdaptiveCardElement element, AdaptiveRenderContext context, AdaptiveRenderArgs renderArgs);
    };

    runtimeclass AdaptiveTextBlockRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveTextBlockRenderer();
    };

    runtimeclass AdaptiveImageRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveImageRenderer();
    };

    runtimeclass AdaptiveImageSetRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveImageSetRenderer();
    };

    runtimeclass AdaptiveContainerRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveContainerRenderer();
    };

    runtimeclass AdaptiveColumnRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveColumnRenderer();
    };

    runtimeclass AdaptiveColumnSetRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveColumnSetRenderer();
    };

    runtimeclass AdaptiveFactRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveFactRenderer();
    };

    runtimeclass AdaptiveChoiceSetInputRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveChoiceSetInputRenderer();
    };

    runtimeclass AdaptiveDateInputRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveDateInputRenderer();
    };

    runtimeclass AdaptiveNumberInputRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveNumberInputRenderer();
    };

    runtimeclass AdaptiveTextInputRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveTextInputRenderer();
    };

    runtimeclass AdaptiveTimeInputRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveTimeInputRenderer();
    };

    runtimeclass AdaptiveToggleInputRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveToggleInputRenderer();
    };

    runtimeclass AdaptiveFactSetRenderer : IAdaptiveElementRenderer, IAdaptiveElementParser
    {
        AdaptiveFactSetRenderer();
    };

    runtimeclass AdaptiveRenderArgs
    { 
        AdaptiveRenderArgs();
        ContainerStyle ContainerStyle{ get; set; };
        IInspectable ParentElement{ get; set; };
    };

    interface IAdaptiveError : IInspectable
    {
        ErrorStatusCode StatusCode{ get; };
        String Message{ get; };
    };

    runtimeclass AdaptiveError : IAdaptiveError
    {
        AdaptiveError();
    };

    interface IAdaptiveWarning : IInspectable
    {
        WarningStatusCode StatusCode{ get; };
        String Message{ get; };
    };

    runtimeclass AdaptiveWarning : IAdaptiveWarning
    {
        AdaptiveWarning();
    };

    runtimeclass WholeItemsPanel : Windows.UI.Xaml.Controls.Panel
    {
        WholeItemsPanel();
        String GetAltText();
        Boolean IsAllContentClippedOut();
        Boolean IsTruncated();
    };
}}}